### ISSUE TITLE
Bug: candidate is always not set in CTLD.pm

### ISSUE THREAD

**Issue by IronDusts** [ktrace/pxmx-ctld#4]
At line 350 of CTLD.pm $candidate is always reported as empty variable and the script is failing because you are using "==" instead of "eq" for checking of the variable is set/empty. 

I have fixed it for me but cannot commit my changes in your repo. Suggest if you still work on this project to fix it. 

The Patch files also needs refreshment, but I don't have the time to create one so I just patched manually.

**Comment by ktrace** [comment]
L350 fixed, patch files refresh later
https://github.com/ktrace/pxmx-ctld/commit/f7966c60cf991e2d95626b7fe62f2402fa73bcda
